tests/test_sqlalchemy_data_layer.py
Hi, so first off, really cool library. Been looking for something that does this for a while. Good stuff 👍  It's midnight where I am right now and I saw you were at 91% test coverage-wise, decided I'd take a stab at it (upped it 1% btw 😎 ). But looking more into, I see you guys have many tests that follow the pattern:
```
def test_sqlalchemy_data_layer_get_object_error(session, person_model):
with pytest.raises(Exception):
dl = SqlalchemyDataLayer(session=session, model=person_model, id_field='error')
dl.get_object(**dict())
```
You're expecting `dl.get_object` to throw an Exception, but it never reaches that far. You're passing `SqlalchemyDataLayer` the wrong format of parameters and that's where the exception is coming from, not `dl.get_object`. I fixed the …
=> added some tests; fixed some errors

flask_rest_jsonapi/decorators.py
In decorators.py, there is no check if the Content-Type is present in the headers, which will raise an uncaught exception if we try to use the API in the browser. This check will make sure that the header is present otherwise it will return the json response with 415
=> Checking if Content-Type is present in the request headers

flask_rest_jsonapi/resource.py
Per the JSON API specification: "Where specified, a meta member can be used .. The value of each meta member MUST be an object" (http://jsonapi.org/format/#document-meta)
=> convert delete method's response meta to an object

flask_rest_jsonapi/decorators.py
JSONAPI 1.0 specification says:
“Clients that include the JSON API media type in their Accept header MUST specify the media type there at least once without any media type parameters.”
That means, that there may be other acceptable MIME types, which the string comparison that was in place before prevented.
This should also help with issue #13.
=> Fix parsing of Accept header.

.travis.yml, flask_rest_jsonapi/data_layers/alchemy.py
This should not impact existing installation, as quoting the sqlalchemy doc: 
> A mapping by default shares the same name for a Column as that of the mapped attribute - specifically it matches the Column.key attribute on Column, which by default is the same as the Column.name.
http://docs.sqlalchemy.org/en/latest/orm/mapping_columns.html
`Column.key == Column.name`
=> Fix #60: Allow renaming columns in Model

tests/test_sqlalchemy_data_layer.py
- Set person missing and default to None in Computer Schema
- Fix typo, the SQLAlchemy model uses .person not .owner
=> Improve delete_relationship_single test

tests/test_sqlalchemy_data_layer.py
- Assert response data is empty
The related view is for person_detail page which does not
exist since the computer is not attached to a person yet during
this test.
=> Improve get_relationship_single_empty test

flask_rest_jsonapi/resource.py, tests/test_sqlalchemy_data_layer.py
=> Fix issue #49

flask_rest_jsonapi/api.py
call `self.init_app(app)` on `Api.__init__` to avoid external call for init_app when using `Api(app)`
also by side-effect, solves the issue with PAGE_SIZE not set when not using `init_app`
current:
```python
app = Flask(__name__)
api = Api(app)
api.init_app(app)  # required to avoid KeyError on app.config['PAGE_SIZE']
```
now:
```python
app = Flask(__name__)
api = Api(app)
```
=> call self.init_app if Api was created with a app

docs/logical_data_abstraction.rst
For Relationship() we need to set the id_field if the field is not named "id".
=> Update logical data abstraction docs to show use of id_field attribute

flask_rest_jsonapi/api.py
When adding decorators to the Api initializer:
api = Api(app, decorators=(my_decorator,))
Decorators would not be added because the as_view class method was executed before the decorators were added to the class and as_view in Flask adds them at that time.
=> Move as_view execution after decorators are added to class object

docs/data_layer.rst
Note that I wasn't able to understand what is the meaining of  *Instead "id" is used.* in
> url_field: the name of the parameter in the route to get value to filter with. Instead "id" is used.
Also the very last sentence: *It is easier to use in the data layer.*, easier than what?
=> Typos and phrasing

README.rst
The Flask-restful was broken, ant it better to use the base readthedocs URL, and the the target project redirect to whatever they think appropriate.
=> Fix links for Flask-restful and Falsk-restless

docs/quickstart.rst, examples/api.py
`requried` reworded to `required`.
=> Fix typo in docs and example

MANIFEST.in
Not including the license file made the tarball illegal; including docs and tests makes it easier and better to integrate into Debian aswell.
=> Complete source tarball.

docs/configuration.rst, flask_rest_jsonapi/resource.py
Until now all exceptions was catched and converted to JsonApiException.
There was no way how to use custom error catcher like Airbrake.
Setting new configuration parameter `CATCH_EXCEPTIONS` to `False` will correct this behaviour. 
Default `CATCH_EXCEPTIONS` is `True` so no breaking changes is introduced.
=> Enable to bypass automatic exception conversion to JsonApiException

flask_rest_jsonapi/resource.py
We've discovered that when trying to implement the PATCH method against a data layer that redefines the `url_field` in a subclass of SqlalchemyDataLayer rather than by passing it in the `data_layer` dict in the subclass of ResourceDetail, the PATCH fails with `KeyError: 'id'` as the alternative field name is ignored. This patch fixes this by always looking in `self._data_layer` for `url_field` which is consistent with where you look for it in other places.
I also had to stringify the id on both sides of the comparison otherwise it failed for integer IDs.
=> PATCH should compare the id using the url_field defined in the data_layer class

flask_rest_jsonapi/data_layers/alchemy.py
Currently the 'eagerload_includes' parameter for a SQLAlchemy data layer can only be set to `False` for a ResourceList. For a ResourceDetail, this results in a 'bool not callable' error. This PR attempts to fix that
=> Allow eagerload_includes: False option on ResourceDetail

flask_rest_jsonapi/resource.py
When this hook was introduced by @kumy  in https://github.com/miLibris/flask-rest-jsonapi/pull/123, it was not added to the `post()` method. I'm pretty sure this is an oversight, as it's just as useful there as anywhere else, and there's no discussion about specifically omitting it.
In fact, the issue referenced (#108) talks specifically about POST.
=> Add before_marshmallow hook to POST handler

flask_rest_jsonapi/decorators.py
When the `ROPAGATE_EXCEPTIONS` is set, it is desirable to re-throw the error such that any registered flask error handlers will take care of it.
This fixes the error described in issue #162.
=> Propagate flask_rest_jsonapi errors to flask

flask_rest_jsonapi/utils.py
Added handling of Decimal type to JSON Encoder (since the switch to 'json.dumps' Decimal type was no longer supported).
=> Added support for Decimal type in JSON encoder

.travis.yml, flask_rest_jsonapi/resource.py, requirements.txt, setup.py, tests/test_sqlalchemy_data_layer.py
* Use Marshmallow 3, and fix code and tests that is tied to Marshmallow 2
* Since we're using Marshmallow 3, and since Python 2 is about to hit EOL, remove it from the Travis tests
* Streamline installation by removing `requirements.txt` and adding additional dev packages to the dev extras
* Add helpful assertion messages to the assert statements in the tests
* Add some more recent versions of Python to Travis
=> Python 3 and Marshmallow 3

flask_rest_jsonapi/api.py, flask_rest_jsonapi/resource.py, tests/test_sqlalchemy_data_layer.py
For example, this lets you do:
```python
class TestResource(ResourceDetail):
""" 
This fake resource always renders a constructor parameter
""" 
def __init__(self, *args, **kwargs):
super().__init__()
self.constant = kwargs.get('constant')
def get(self):
return self.constant
api.route(TestResource, 'resource_kwargs', '/resource_kwargs', resource_kwargs={
'constant': 'hello!'
})
```
Basically this is helpful if you ever want to fully customize a resource object.
=> Allow custom resource constructor args

flask_rest_jsonapi/querystring.py
This is a simple and quick idea to support "IN" clause based on jsonapi specification:
filter[id]=1,2,3
Hope this helps
=> Feature to support 'in' clause based on jsonapi filter=1,2,3 - BUG: #189
